graph TD
    Start((START)) --> StatsHistory[履歴の集計]
    StatsHistory -->|必要額 = 今までの最大値<br>（履歴無しなら default を使う）| WrappedAmount{Wrapped の残高}
    WrappedAmount -->|必要額の10倍より大きい| Harvest
    WrappedAmount -->|必要額以上で<br>必要額の10倍以下| End((END))
    WrappedAmount -->|必要額より小さい| Refill

    subgraph Refill[補充]
        CheckNative{ネイティブ残高の確認}
        CheckNative -->|足りる| DepositFull[必要なだけ Deposit]
        CheckNative -->|足りない| DepositLess[minimum だけ残して Deposit]
    end

    subgraph Harvest[収穫]
        Withdraw --> NativeAmount{Native が<br>必要額の100倍より大きく<br>前回の収穫から<br>24時間以上経過}
        NativeAmount -->|YES| Back
        NativeAmount -->|NO| NoAction
    end

    Refill --> End
    Harvest --> End